apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    app: post-service
spec:
  selector:
    {{- include ".helm.selectorLabels" . | nindent 8 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}