apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata:
      labels:
        app: app-v1
    spec:
      containers:
        - name: app-v1
          image: app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
